### ISSUE TITLE
Fix textinput hidden by iOS keyboard

### ISSUE THREAD

**Issue by AtlantisPleb** [OpenAgentsInc/arcade#120]
Tapping on the chat input bar hides the input behind the keyboard. You may need to review the [Screen](https://github.com/infinitered/ignite/blob/master/docs/Components-Screen.md) props which should handle this. Looks like the avoidingview is moving up, but not far enough.

The default behavior of the iOS emulator is to use your system keyboard so these keyboard bugs are easy to overlook in development.

You can use the iPhone keyboard instead by going into the emulator menu I/O > Keyboard > Disable "Connect hardware keyboard"

https://github.com/ArcadeLabsInc/arcade/assets/14167547/67afd819-8cb7-44fd-98a6-4b4350aadb82

**Comment by ArcadeCityMayor** [comment]
Solved in #121
